### ISSUE TITLE
Brittle bank-2-merchant flows

### ISSUE THREAD

**Issue by cyberphone** [w3c/webpayments-methods-credit-transfer-direct-debit#41]
If step 5 or 6 in the sequence diagram fails reaching their destination, the Bank will have a different opinion than the Merchant about the status of the payment.  How are you going to deal with that?

**Comment by ianbjacobs** [comment]
Payment Request API includes a paymentRequestID that serves to help merchants and payment service providers reconcile their views of payments.

**Comment by cyberphone** [comment]
Yes, but it is the _user_ that will have clear up this mess and that won't be fun or easy.  Effectively this method presumes that this situation [almost] never happens which may be correct.

**Comment by mattsaxon** [comment]
I'm not clear that there is anything to "clear-up" apart from better communication of the failure. That is because when step 5 starts, the transaction has been completed and the rest of the flow from step 7 should complete as expected resulting in the contract being fulfilled.

However, there is risk here that the user will restart the transaction, perhaps resulting in duplicate charges and service delivery.

A typical way that such issue are handled today is that there is an additional notification (usually to an email address, but it could be an SMS message for example) to the payer on transfer. This could be shown as coming from the Payer's Bank (which typically has the necessary information already, e.g. email address or phone number of the payer). It is also possible for the Payee to provide such notification. 

I suggest we add an extra, optional, step after both step 7 and step 8 for notifications to the payer fromn the Bank and Payer respectively.

**Comment by ianbjacobs** [comment]
@mattsaxon, that seems fine. Would you produce the new diagram? Thanks!

Ian

**Comment by mattsaxonwp** [comment]
I would be happy to do so, please assign to me (@mattsaxonwp) and can you add me as an admin to this repo please? I can't guarantee when I'll do it though, sorry, I'll try to prior to the f2f or at least during it.

**Comment by ianbjacobs** [comment]
Hi @mattsaxon,

Sorry for the delay...apparently my notification settings were not correct and I did not see this until now. :(

You are already Admin for this repo. 

Please consider that you have the action:
 https://github.com/w3c/webpayments-methods-credit-transfer-direct-debit/milestones

Ian

**Comment by mattsaxon** [comment]
Notifications added (to Push only at this stage) in PR https://github.com/w3c/webpayments-methods-credit-transfer-direct-debit/pull/54

**Comment by mattsaxon** [comment]
Closed via PR #56.
