### ISSUE TITLE
Is there a need for a basic-credit-transfer (form filler) PMI?

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-credit-transfer-direct-debit#61]
In addition to current push and pull model in the spec (where there is a payment app that does some 'real' work), do we need a simpler model that just allows the browser to perform form-filler type processing supplying the payer's account details to the merchant?

I'm not aware of any scheme, bank or PSP that supports this type of model today, though Direct Debit could work this way.

**Comment by CYV** [comment]
This is an interesting issue. Let assumed we have a form filler inbsted of an App. This means that data (fields) will be sent to the merchant in order for it to initiate the credit transfer. In Europe, this is possible through the DSP2 regulation: actually, the merchant will delegate the initiation of the credit-transfer to a PISP (Payment Initiation Service Provider, body with specific regulation, but it could be also the merchant Bank).
To do that, I think we should add new fields: 
- the "payerBankCode" : necessary for the PISP to find the payerBank and connect to its initiation-payement-API (DSP2 API)
- the  "payerAccountNumber": necessary for the PISP to tel the payerBank who is the payer
- the "PayerName": necessary for the payerBank to be sure that the accountnumber is for this client

When there is an App, the App should be parameterized in order to connect to the bank of the payer (a simple URL at installation or more). When only a form filler, it is not possible for the payer to know the URL of its bank. So, the payer will give his banking details, in order for the PISP to look up at directories and find the right bank.

the form filler initiative is a good idea to explore the "pull credit transfer".

**Comment by ianbjacobs** [comment]
Hi @mattsaxon and @CYV,

I am not sure what "form filler" means. Does it mean the browser will natively implement the payment method and provide a form for the user to input data?

@CYV, two of the three fields you listed are already in the payment response data (payerBankCode and payerName). Are you suggesting that we add payerAccountNumber, which might be used
either by the browser or by third party payment apps?

Ian

**Comment by ianbjacobs** [comment]
We have started work on a simpler credit transfer spec that is designed for less data when PISPs are regulated and have relationships such that they have the data:
  https://w3c.github.io/payment-method-pisp-credit/

**Comment by mattsaxon** [comment]
Given that this spec is now created, I propose we close this issue
